### ISSUE TITLE
Algumas ideias para melhorar o curso

### ISSUE THREAD

**Issue by jtrecenti** [curso-r/main-visualizacao#1]
Esse curso tem muito conteúdo e é difícil se aprofundar. O que eu acho que devemos fazer

1. Abraçar essa característica do curso, deixando claro que a maior parte é de conhecimento horizontal.
2. Escolher bem (e deixar explícito) o que queremos aprofundar.

## O que queremos que seja horizontal?

- especificidades dos outputs: officedown, pagedown, bookdown, e talvez até xaringan (com muita dor)
- miscelanea de visualização: plotly, flextable, leaflet
- extensoes do ggplot2: gghighlight, ggrepel, gganimate
- pacotes de visualização para deixar de fora, mas citar que existem: gt, gtsummary, DT, reactable, highcharter

Para as coisas horizontais, podemos deixar um tempo limitado (e.g. 15 min) para explicar e mostrar um exemplo. Dessa forma temos mais previsibilidade para a aula. 1 exercício por exemplo, podendo ser em sala ou para casa

## O que queremos que seja vertical?

- Fundamentos do RMarkdown: YAML, chunks, linguagem .md, parâmetros, o pacote knitr (especialmente include_graphics, kable, chunk_options)
- temas do ggplot2: reduzir a parte de revisão e aumentar exemplos com temas
- mapas com sf: aqui acho que o volume de conteúdo está bom; temos apenas de melhorar os exemplos

Sobre aulas, inverter aula 2 e 3:

- Aula 1. Somente outputs html, pdf e docx padrão. Tentar fazer funcionar tudo que pode dar errado (latex, svglite, webshot)
- Aula 2. Overview dos diferentes outputs (officedown, pagedown, bookdown, xaringan) e CSS
- Aula 3. ggplot2 + mapas
- Aula 4. Miscelanea + web

Também precisamos fixar as bases de dados. Sugestão: bases do abjData (posso colocar no CRAN para facilitar)

**Comment by azeloc** [comment]
Tenho uma pergunta e um comentário.

Vocês sentiram que as pessoas ja tinham conhecimento previo de ggplot2 ou teve muita gente que teve o primeiro contato nesse curso?

comentario:

No semestre que vem esse curso vai ter 5 aulas.

**Comment by jtrecenti** [comment]
parecia que ja tinham conhecimento previo de ggplot2

sobre a aula 5 beleza, podemos podemos fazer aula 2 e 3 em aula 2, 3 e 4 colocando mais exemplos de output e subindo as extensoes de ggplot para aula 4 ao inves de deixar na miscelanea

**Comment by beatrizmilz** [comment]
não ficou claro pra mim o que quer dizer com conteúdo vertical e horizontal..

**Comment by jtrecenti** [comment]
vertical: profundo, detalhado, longo
horizontal: superficial, curto

**Comment by beatrizmilz** [comment]
- [x] Remover alguns extras do slide

**Comment by jtrecenti** [comment]
Resolvido com separação do curso e nova versão de vis
