### ISSUE TITLE
Arrumar o exemplo do gghighlight no script da aula de miscelanea

### ISSUE THREAD

**Issue by beatrizmilz** [curso-r/main-visualizacao#13]

**Comment by azeloc** [comment]
Qual foi o erro que deu aí? Aqui primeiro foi

```
Error in repel_boxes2(data_points = as.matrix(x$data[, c("x", "y")]),  : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'
```

Daí eu reinstalei no Rcpp e foi. Joguei no google e achei isso:

https://stackoverflow.com/questions/68416435/rcpp-package-doesnt-include-rcpp-precious-remove

**Comment by beatrizmilz** [comment]
Fe, olhei aqui e o Julio arrumou ja! o erro era outro.

https://github.com/curso-r/main-visualizacao/commit/90475ec8c91796e61bf605eb5d4c047036e178b2
Vou fechar a issue pq ele resolveu ja
