### ISSUE TITLE
Sugestão de plano de aulas da nova versão

### ISSUE THREAD

**Issue by jtrecenti** [curso-r/main-visualizacao#14]
O curso de visualização de dados possui 4 aulas, de 3 horas cada, totalizando 12 horas de curso. Nosso objetivo será trabalhar nas dimensões abaixo:

1. Análise exploratória
    - Teoria:
      - análise exploratória e análise explicativa
      - tipos de visualização
      - gráficos bons e ruins
    - Prática:
      - revisão de ggplot2
      - live coding de análise exploratória
2. Análise explicativa
    - Teoria:
      - coerência visual
      - otimização visual
      - recursos pré-atentativos
      - temas do ggplot2
          - ggthemes
          - hrbrthemes
    - Prática
      - otimização de 1 ou 2 gráficos da aula 1
3. Extensões do ggplot2
    - patchwork
    - ggrepel
    - ggridges
    - ggalt
    - geom_sf
    - gganimate
    - ggtext
    - Dinâmica: definição e exemplo para cada pacote
4. Visualizações interativas
    - leaflet
    - plotly
    - highcharter
    - reactable
    - Dinâmica: definição e exemplo para cada pacote

Conteúdos extras:

    - (teoria) feature engineering através da visualização
    - (teoria) tradução de perguntas de pesquisa
    - live de ggplot qualquer coisa
    - esquisse

**Comment by beatrizmilz** [comment]
No oferecimento de 2021, o conteúdo sobre geom_sf foi bem extenso (cerca de 1h). Para dar certo no tempo seria bom alterar para um exemplo mais simples.

Na loja aparece introdução à data storytelling também: https://loja.curso-r.com/visualizac-o-de-dados.html 
 Ideia: deixar uma introdução do conceito na aula 1, mostrar exemplos práticos na oficina de ds

**Comment by jtrecenti** [comment]
incorporado na nova versão do curso
