### ISSUE TITLE
Ideia da dinamica nova do curso

### ISSUE THREAD

**Issue by azeloc** [curso-r/main-visualizacao#2]
- Na primeira aula mexer em apenas um .Rmd que começa do 0 e knita para .html, .doc, .ppt. Esse script vai ser o apoio para explicar a estrutura de .Rmd.
     - Esse script vai ser onde vamos escrever todos os códigos de exemplo do curso.
     - Precisamos montar um .Rmd bem completo com base nos exemplos que já estão prontos.
     - Esse script pode partir do conteúdo que está na pasta 04-rmarkdown-xaringan/index.Rmd.
     - Esse .Rmd de referência precisa knitar bonitinho pra .doc e .ppt também com no máximo três alterações no cabeçalho e usando templates. Dá pra usar os templates que já estão na pasta mesmo.
     - mostrar o output com o prettydoc
- Na segunda aula vamos de falar de CSS, xaringan, **pagedown** e como publicar os seus relatório online no netlify drop.
- Na terceira aula a gente vai colocar nesse(s) .Rmd o conteúdo do script do ggplot2. Tem que adaptar esse .R pra .Rmd
- Na quarta aula a gente fala de sf e para isso tem que compatibilizar os scripts de sf e garantir que roda em qualquer computador. Seria legal usar o abjData.
- Na quinta aula trabalhamos em flexdashboard, podemos dar um exemplo de rticles e o flex é preenchido com as extensões do ggplot2: {gghighlight, ggrepel, gganimate}, plotly.

- Verificar se tem algo deste curso que valha a pena colocar no livro (e colocar dps)

**Comment by beatrizmilz** [comment]
- na aula 2, xaringan fica no final, usar um template do garrick

**Comment by beatrizmilz** [comment]
na aula 5, mostrar o exemplo que gera o PDF usando o script da aula 1

**Comment by jtrecenti** [comment]
Resolvido com split do curso e nova versão de vis
