### ISSUE TITLE
Refatorar os scripts de SF

### ISSUE THREAD

**Issue by azeloc** [curso-r/main-visualizacao#3]
Atualmente os dois scripts são ligeiramente diferentes e a gente precisa que vire um só. Os conteúdos estão bons, não precisa adicionar mais coisa explicação, teoria nem nada.

Seria legal pensar em um exemplo menos focado em São Paulo. Ideia: pegar 5 slides.

**[PRIORIDADE MENOR]** Esse conteúdo ainda não tem slides, mas não precisamos nos preocupar com isso até terminar de arrumar todos os conteúdos do curso.

**Comment by beatrizmilz** [comment]
https://github.com/curso-r/main-visualizacao/blob/master/novos_exemplos_de_aula/mapas-com-ggplot2.R

- Usei apenas dados do geobr e do abjData
- Não usei sf de municípios: muito pesado. usei de estados.
- não usar patchwork nessa aula!!
- removi o exemplo que importa um shapefile. acham bom deixar?

**Comment by beatrizmilz** [comment]
https://github.com/curso-r/main-visualizacao/blob/master/novos_exemplos_de_aula/mapas-com-ggplot2.Rmd

@azeloc o que acha?

Versão em html se facilita pra ver:
https://curso-r.github.io/main-visualizacao/novos_exemplos_de_aula/mapas-com-ggplot2.html
