### ISSUE TITLE
Refatorar aula de ggplot2

### ISSUE THREAD

**Issue by azeloc** [curso-r/main-visualizacao#5]
Precisamos colocar o scripts de ggplot2 atuais num .Rmd

Reduzir a parte de revisão e aumentar exemplos com temas

**Comment by beatrizmilz** [comment]
separei conteudo de temas e de ggplot basico. conteudo de ggplot basico foi pra um arquivo de revisao. conteudo que fala de temas, cores e escalas ficou no arquivo da aula, e transformado em um .Rmd
o exemplo de gghighlight foi movido para a aula de miscelanea, na parte de extensoes pra ggplot2
falta aumentar exemplos de temas
