### ISSUE TITLE
Adaptar os exemplos antigos de flexdashboard

### ISSUE THREAD

**Issue by azeloc** [curso-r/main-visualizacao#7]
Agora o flexdashboard vai mostrar também as extensões de ggplot2

Vamos adaptar os códigos prontos nesse arquivo: https://github.com/curso-r/202103-visualizacao/blob/master/aula_extra/flex.Rmd

**Comment by beatrizmilz** [comment]
Na conversa com o Julio, pensamos em nao fazer junto. no começo da aula mostrar um live coding com flex, que não demore tanto. Aí o restante da aula focamos nas miscelaneas que estão no arquivo na pasta de exemplos_de_aula

**Comment by beatrizmilz** [comment]
fechei sem querer haha
